# Generated by Django 4.1.1 on 2022-09-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('ct', models.CharField(max_length=100)),
                ('num', models.CharField(max_length=15)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
