# Generated by Django 4.1.1 on 2023-02-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_contact_date_remove_contact_desc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pid", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("details", models.CharField(max_length=2000)),
                ("price", models.IntegerField()),
            ],
        ),
    ]
