# Generated by Django 4.1.1 on 2023-02-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_product_details_alter_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="details",
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
